In [1]:
import os,sys,shutil
import numpy as np

In [2]:
root_dir = '/scratch/zz737/fiar/'


In [56]:
subdirs = os.listdir(root_dir)

In [52]:
des_dir = '/scratch/zz737/fiar/tournaments/tournament_4/'

In [27]:
import re

In [47]:
re.sub('id.|id..','id123',sc)

'/scratch/zz737/fiar/run-3752917/scratch/zz737/fiar/tournaments/tournament_4/checkpoints_mcts100_cpuct2_id123'

In [58]:
dir_part = 'scratch/zz737/fiar/tournaments/tournament_4/'
for dir in subdirs:
    if dir.startswith('run'):
        run_num = dir.split('-')[1]
        subdir = os.path.join(root_dir,dir,dir_part)
        if os.path.exists(subdir):
            model_dir = os.listdir(subdir)
            if len(model_dir) > 0:
                model_dir_name = model_dir[0]
                sc = os.path.join(subdir,model_dir_name)
#                 model_dir_name_new = f'id-{run_num}'
#                 model_dir_name_new = re.sub('id.|id..',model_dir_name_new,sc)  
    #             os.rename(sc,model_dir_name_new)
                shutil.move(sc,des_dir)
                

In [68]:
subdirs = os.listdir(des_dir)

In [110]:
dir

'checkpoints_mcts100_cpuct2_id-3754965'

In [69]:
for dir in subdirs:
    model_dir = os.path.join(des_dir,dir)
    model_fn_l =os.listdir(model_dir)
    if len(model_fn_l) > 20:
#         print(model_dir)
#         shutil.rmtree(model_dir)
        model_fn_l

In [108]:
iter_max = 0
for fn in model_fn_l:
    if fn.endswith('examples'):
        half = fn.split('_')[1]
        iter = int(half.split('.')[0])
        if iter > iter_max:
            iter_max = iter

In [115]:
!python ../batch_jobs/write_continue_training_sz.py

['/scratch/zz737/fiar/tournaments/tournament_4/checkpoints_mcts100_cpuct2_id-3754964', '/scratch/zz737/fiar/tournaments/tournament_4/checkpoints_mcts100_cpuct2_id-3752918', '/scratch/zz737/fiar/tournaments/tournament_4/checkpoints_mcts100_cpuct2_id-3752919', '/scratch/zz737/fiar/tournaments/tournament_4/checkpoints_mcts100_cpuct2_id-3752921', '/scratch/zz737/fiar/tournaments/tournament_4/checkpoints_mcts100_cpuct2_id-3753063', '/scratch/zz737/fiar/tournaments/tournament_4/checkpoints_mcts100_cpuct2_id-3752985', '/scratch/zz737/fiar/tournaments/tournament_4/checkpoints_mcts100_cpuct2_id-3752917', '/scratch/zz737/fiar/tournaments/tournament_4/checkpoints_mcts100_cpuct2_id-3751934', '/scratch/zz737/fiar/tournaments/tournament_4/checkpoints_mcts100_cpuct2_id-37549660', '/scratch/zz737/fiar/tournaments/tournament_4/checkpoints_mcts100_cpuct2_id-3754965']
[49, 49, 48, 47, 51, 48, 44, 15, 48, 51]


In [116]:
dirname = 'abc'
scname ='abc1.txt'
os.path.join(dirname,scname)

'abc/abc1.txt'

In [70]:
import argparse

In [72]:
my_parser = argparse.ArgumentParser(description='List the content of a folder')

# Add the arguments
my_parser.add_argument('Path',
                       metavar='path',
                       type=str,
                       help='the path to list')

# Execute the parse_args() method
# args = my_parser.parse_args()

_StoreAction(option_strings=[], dest='Path', nargs=None, const=None, default=None, type=<class 'str'>, choices=None, help='the path to list', metavar='path')

In [90]:
!python test.py -va 1 op
# !python test.py op

{'Path': 'op', 'value': True}
The path specified does not exist


In [91]:
class dotdict(dict):
    def __getattr__(self, name):
        return self[name]


In [4]:
sys.path.append('../classes')

In [12]:
import tournament
import importlib
importlib.reload(tournament)
from beck.beck_game import BeckGame as Game

{'mcts100_cpuct1': [1, 2, 3, 4, 6, 7, 9, 11, 12, 16, 18, 21, 25, 28, 29, 30, 37, 38, 39, 45, 47], 'mcts100_cpuct2': [1, 2, 3, 4, 6, 8, 12, 14, 15, 16, 21, 22, 24, 26, 27, 30, 32, 35, 39], 'mcts100_cpuct3': [1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 16, 17, 18, 20, 21, 25, 26, 28, 32, 34, 35, 36], 'mcts25_cpuct1': [1, 2, 3, 4, 9, 11, 13, 14, 16, 19, 22, 25, 28, 29, 31, 37, 39, 45, 59, 61], 'mcts50_cpuct1': [1, 2, 3, 4, 5, 6, 7, 9, 10, 13, 17, 18, 20, 21, 23, 25, 28, 29, 31, 37, 39, 41, 44, 45, 47, 48, 53], 'mcts80_cpuct1': [1, 2, 3, 4, 5, 7, 8, 9, 10, 13, 16, 19, 20, 21, 23, 24, 28, 34, 35, 36, 40], 'mcts80_cpuct2': [1, 2, 5, 6, 8, 10, 12, 13, 15, 17, 18, 19, 22, 25, 28, 30, 31, 34, 37, 38, 39, 40, 43, 45, 46, 51], 'mcts80_cpuct3': [1, 2, 5, 6, 7, 9, 12, 13, 14, 19, 21, 22, 23, 24, 26, 27, 28, 35, 36, 42, 43, 47, 49, 50, 51, 53, 54, 55, 56, 57]}
189 participant iterations!


In [10]:
g  = Game(4,9,4)

In [29]:
participants_dir = '/scratch/zz737/fiar/tournaments/tournament_4/checkpoints_mcts100_cpuct2_id-3751934'
participant_iter = 'mcts100_cpuct2;50'
ai, val_func = tournament.get_player(g,participants_dir,participant_iter)

In [30]:
ai(b)

30

In [31]:
val_func.predict(b)

(array([2.15305974e-07, 4.53008306e-06, 2.87621191e-07, 2.45702922e-01,
        6.97864209e-07, 2.56191373e-01, 1.03578685e-07, 1.35560049e-05,
        3.68918478e-08, 5.10552240e-07, 4.17803854e-08, 2.48453738e-08,
        8.17030852e-08, 1.82850172e-07, 2.71402048e-08, 5.66386449e-09,
        2.02496029e-08, 9.30749096e-08, 5.75965089e-07, 6.30031636e-08,
        4.25828617e-08, 4.94683583e-08, 3.14616067e-08, 1.32406285e-07,
        5.32476676e-08, 4.31371694e-09, 6.12165394e-08, 1.81682267e-07,
        8.71896555e-06, 6.54866881e-08, 2.53237218e-01, 1.40091046e-07,
        2.44831651e-01, 2.48782015e-07, 6.05594596e-06, 9.27069621e-09],
       dtype=float32),
 array([0.31315565], dtype=float32))

In [17]:
b = g.getInitBoard()

In [18]:
b

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [32]:
import os
csv_dirs = '/scratch/zz737/fiar/tournaments/results/tournament_4'


In [42]:
for d in os.listdir(csv_dirs):
    dd = os.path.join(csv_dirs,d)
    try:
        for f in os.listdir(dd):
            os.remove(os.path.join(dd,f))
    except:
        pass

In [43]:
dd

'/scratch/zz737/fiar/tournaments/results/tournament_4/checkpoints_mcts100_cpuct2_id-3754965'

In [44]:
f

'pgn.pgn'

In [45]:
participants_dir = '/scratch/zz737/fiar/tournaments/tournament_4' 
results_dir = '/scratch/zz737/fiar/tournaments/results/tournament_4' 
moves_dir = '/scratch/zz737/fiar/tournaments/tournament_4/moves/raw/'


In [48]:
model_copy_list  = os.listdir(participants_dir) # get ['checkpoints_mcts100_cpuct2_id-3751934', ...]
model_copy_list = [x for x in model_copy_list if x.startswith('checkpoints')][:1] # only select checkpoints # [[testing!!!]] only select :1 to see if it runs

script_dir_name = 'script_tournament_parallel_within_modelclass'

In [49]:
model_copy = model_copy_list[0]

In [51]:
sys.path.append('../batch_jobs')

In [53]:
import write_tournament_parallel_within_modelclass_sz as wr

In [54]:
participant_iters, niters= wr.get_participant_iters(model_copy, participants_dir, results_dir, moves_dir)

['mcts100_cpuct2;1', 'mcts100_cpuct2;2', 'mcts100_cpuct2;3', 'mcts100_cpuct2;4', 'mcts100_cpuct2;5', 'mcts100_cpuct2;6', 'mcts100_cpuct2;7', 'mcts100_cpuct2;8', 'mcts100_cpuct2;9', 'mcts100_cpuct2;10', 'mcts100_cpuct2;11', 'mcts100_cpuct2;12', 'mcts100_cpuct2;13', 'mcts100_cpuct2;14', 'mcts100_cpuct2;15', 'mcts100_cpuct2;16', 'mcts100_cpuct2;17', 'mcts100_cpuct2;18', 'mcts100_cpuct2;19', 'mcts100_cpuct2;20', 'mcts100_cpuct2;21', 'mcts100_cpuct2;22', 'mcts100_cpuct2;23', 'mcts100_cpuct2;24', 'mcts100_cpuct2;25', 'mcts100_cpuct2;26', 'mcts100_cpuct2;27', 'mcts100_cpuct2;28', 'mcts100_cpuct2;29', 'mcts100_cpuct2;30', 'mcts100_cpuct2;31', 'mcts100_cpuct2;32', 'mcts100_cpuct2;33', 'mcts100_cpuct2;34', 'mcts100_cpuct2;35', 'mcts100_cpuct2;36', 'mcts100_cpuct2;37', 'mcts100_cpuct2;38', 'mcts100_cpuct2;39', 'mcts100_cpuct2;40', 'mcts100_cpuct2;41', 'mcts100_cpuct2;42', 'mcts100_cpuct2;43', 'mcts100_cpuct2;44', 'mcts100_cpuct2;45', 'mcts100_cpuct2;46', 'mcts100_cpuct2;47', 'mcts100_cpuct2;48', 

In [59]:
import pandas as pd
results_name = 'round_robin'

In [60]:
results_df = pd.DataFrame(index=participant_iters, columns=participant_iters)
results_df.to_csv(os.path.join(results_dir, results_name + '.csv'))

In [ ]:
results_df

In [63]:
results_dir

'/scratch/zz737/fiar/tournaments/results/tournament_4'

In [61]:
model_copy

'checkpoints_mcts100_cpuct2_id-3754964'

In [64]:
ngames=1

In [71]:
!python -W ignore -u ../classes/tournament_parallel_within_modelclass.py 0 $model_copy $participants_dir $results_dir $moves_dir round_robin $ngames




{'mcts100_cpuct1': [1, 2, 3, 4, 6, 7, 9, 11, 12, 16, 18, 21, 25, 28, 29, 30, 37, 38, 39, 45, 47], 'mcts100_cpuct2': [1, 2, 3, 4, 6, 8, 12, 14, 15, 16, 21, 22, 24, 26, 27, 30, 32, 35, 39], 'mcts100_cpuct3': [1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 16, 17, 18, 20, 21, 25, 26, 28, 32, 34, 35, 36], 'mcts25_cpuct1': [1, 2, 3, 4, 9, 11, 13, 14, 16, 19, 22, 25, 28, 29, 31, 37, 39, 45, 59, 61], 'mcts50_cpuct1': [1, 2, 3, 4, 5, 6, 7, 9, 10, 13, 17, 18, 20, 21, 23, 25, 28, 29, 31, 37, 39, 41, 44, 45, 47, 48, 53], 'mcts80_cpuct1': [1, 2, 3, 4, 5, 7, 8, 9, 10, 13, 16, 19, 20, 21, 23, 24, 28, 34, 35, 36, 40], 'mcts80_cpuct2': [1, 2, 5, 6, 8, 10, 12, 13, 15, 17, 18, 19, 22, 25, 28, 30, 31, 34, 37, 38, 39, 40, 43, 45, 46, 51], 'mcts80_cpuct3': [1, 2, 5, 6, 7, 9, 12, 13, 14, 19, 21, 22, 23, 24, 26, 27, 28, 35, 36, 42, 43, 47, 49, 50, 51, 53, 54, 55, 56, 57]}
189 participant iterations!
['0', 'checkpoints_mcts100_cpuct2_id-3754964', '/scratch/zz737/fiar/tournaments/tournament_4', '/scratch/zz737/fiar/tourn

^C
Traceback (most recent call last):
  File "../classes/tournament_parallel_within_modelclass.py", line 118, in <module>
    play_ai_round_parallel(int(args[0]), *args[1:-1],int(args[-1])) # last one, ngames need to be turned into int
  File "../classes/tournament_parallel_within_modelclass.py", line 109, in play_ai_round_parallel
    results_df.loc[p1, p2] += tournament.play_game(g, participants_dir, p1, p2, moves_dir=moves_dir) #[SZ] changed to add instead of assignment, to accumulate result
  File "/home/zz737/projects/fiar/4IAR-RL/classes/tournament.py", line 114, in play_game
    win_res = arena.playGameSave(verbose=show_game,nnet=nnet_l,subjectID_l=[participant_iter_1,participant_iter_2],fd=moves_dir) # if fd not exists, should be automatically created
  File "/home/zz737/projects/fiar/4IAR-RL/classes/arena.py", line 35, in playGameSave
    win_result, moves_result = self.playGame(verbose=verbose, nnet=nnet, is_save_moves=True)
  File "/home/zz737/projects/fiar/4IAR-RL/classes/a

In [68]:
!ls ../batch_jobs

__pycache__	      run_training.s
combine_params.py     run_training_sz.s
compute_depth.sh      script_autofit_within_modelclass
compute_depth_new.sh  script_tournament_parallel_within_modelclass
continue_training_sz  write_auto_fit_within_modelclass_sz.py
create_splits.py      write_continue_training_sz.py
run_round_robin.s     write_tournament_parallel_within_modelclass_sz.py
